#!/bin/bash
speed=.1
usr=`whoami`
if [ $# != 1 ]; then
    rsize=500;
else 
    #rsize=$1;
    rsize=$1;
fi

while [ 1 ];
do
   rstatus=`squeue -u $usr -p bii -o "%t" -h | grep R | wc -l`
   qstatus=`squeue -u $usr -p bii -o "%t" -h | grep PD | wc -l`

   ((active=rstatus+qstatus))

   if [[ $active -ge $rsize ]]; then
   echo -ne "\r\033[K|o            $rstatus running and $qstatus in queue." 
      sleep .5;
   echo -ne "\r\033[K\ o           $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K\  o          $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K\   o         $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K\    o        $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K|     o       $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K|      o      $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K|       o     $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K|        o    $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K|         o   $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K|          _  $rstatus running and $qstatus in queue." 
   echo -ne "\r\033[K|          ^  $rstatus running and $qstatus in queue." 
      sleep $speed;
   echo -ne "\r\033[K|          _  $rstatus running and $qstatus in queue." 
      sleep 1;
   else
      break;
   fi
done
